---
- name: Setup EC2 Instance
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Use system Python for facts gathering
  tasks:
    - name: Remove Previous Attempted Installation
      command: rm -rf /usr/src/Python-3.9.13

    - name: Install Prerequisites
      yum:
        name:
          - gcc
          - openssl-devel
          - bzip2-devel
          - libffi-devel
          - wget
        state: present

    - name: Download Python source
      get_url:
        url: https://www.python.org/ftp/python/3.9.13/Python-3.9.13.tgz
        dest: /usr/src/Python-3.9.13.tgz

    - name: Extract Python source
      unarchive:
        src: /usr/src/Python-3.9.13.tgz
        dest: /usr/src/
        remote_src: yes

    - name: Configure Python
      command: ./configure --with-openssl=/usr/include/openssl
      args:
        chdir: /usr/src/Python-3.9.13

    - name: Build Python
      command: make
      args:
        chdir: /usr/src/Python-3.9.13

    - name: Install Python
      command: make altinstall
      args:
        chdir: /usr/src/Python-3.9.13
      notify:
        - Check Python Installation

    - name: Verify Python 3.9 Installation
      command: /usr/local/bin/python3.9 --version
      register: python_version
      ignore_errors: yes

    - name: Debug Python Installation
      debug:
        msg: "Python 3.9 Installation Path: {{ python_version.stderr }}"
      when: python_version.failed

    - name: Update PATH
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH="/usr/local/bin:$PATH"'
        create: yes

    - name: Reload bashrc
      command: source ~/.bashrc
      changed_when: false

    - name: Install pip for Python 3.9
      command: /usr/local/bin/python3.9 -m ensurepip

    - name: Upgrade pip for Python 3.9
      command: /usr/local/bin/pip3.9 install --upgrade pip

    - name: Install/Upgrade requests library for Python 3.9
      command: /usr/local/bin/pip3.9 install requests

    - name: Create MongoDB repository
      copy:
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://pgp.mongodb.com/server-7.0.asc
        dest: /etc/yum.repos.d/mongodb-org-7.0.repo
      notify: Update package index

    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: present

    - name: Start MongoDB service
      systemd:
        name: mongod
        state: started
        enabled: yes

    - name: Install Docker if not installed
      package:
        name: docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create docker group if it doesn't exist
      group:
        name: docker
        state: present

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Remove existing container 'booking-app' if exists
      command: docker rm -f booking-app
      ignore_errors: yes

    - name: Docker Hub login
      command: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      ignore_errors: yes

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: wassimhassin/booking
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: booking-app
        image: wassimhassin/booking:latest
        state: started
        published_ports:
          - "8000:8000"

    - name: Check logs of the 'booking-app' container
      command: docker logs booking-app
      register: container_logs
      ignore_errors: yes

    - name: Display logs of 'booking-app'
      debug:
        msg: "{{ container_logs.stdout }}"

  handlers:
    - name: Check Python Installation
      command: ls -l /usr/local/bin/python3.9
      register: python_check
      ignore_errors: yes

    - name: Debug Python Installation
      debug:
        msg: "Python 3.9 Installation Check: {{ python_check.stdout }}"
      when: python_check.failed

    - name: Update package index
      yum:
        name: '*'
        state: latest